trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  continueOnError: false
  inputs:
    sourceFolder: 'src' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'liquidlogic AWS account'
    regionName: 'eu-west-1'
    awsCommand: 'cloudformation'
    awsSubCommand: 'package'
    awsArguments: '--template-file src/cfn-template.yml --s3-bucket cfn-templates --output-template-file $(Build.ArtifactStagingDirectory)/test-packaged-template.json'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
