AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Description:
  Defines the resources needed to define a route in WS API

Parameters:
  WebsocketsApiId:
    Type: String
    Description: The Id of the websockets API
  LambdaArn:
    Type: String
    Description: The ARN of the lambda to use in the route
  LambdaName:
    Type: String
    Description: The name of the lambda to use in the route
  RouteKey:
    Type: String
    Description: The key to invoke the route
    
Resources:

  RouteIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref WebsocketsApiId
      Description: Lambda Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations"

  Route:
    Type: 'AWS::ApiGatewayV2::Route'
    DependsOn:
      - RouteIntegration
    Properties:
      ApiId: !Ref WebsocketsApiId
      RouteKey: !Ref RouteKey
      AuthorizationType: NONE
      Target: !Sub "integrations/${RouteIntegration}"

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaName
      Principal: apigateway.amazonaws.com
