AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Description:
  Defines the resources for the Leaphy Robocoder Websockets API

# TODO
# - Add compile target S3 bucket
# - Define function names for lambdas
# - Point compile lambda to non-test layer

Parameters:
  EnvironmentParameter:
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod
    Description: Enter the environment this template should be deployed to. Default is test
  CompileLayerParameter:
    Type: String
    Default: arn:aws:lambda:eu-west-1:728909196542:layer:test-layer:17
    Description: Enter the layer used as custom runtime for the Compile lambda

Resources:
  WebsocketsAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${EnvironmentParameter}-robocoder-ws-api"
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      ApiKeySelectionExpression: $request.header.x-api-key

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ["lambda.amazonaws.com" ]
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: AllowAllForWebsocketRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: "*"
              - Effect: Allow
                Action: xray:*
                Resource: "*"
              - Effect: Allow
                Action: dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action: 'execute-api:ManageConnections'
                Resource: 'arn:aws:execute-api:*:*:*/@connections/*'
              - Effect: Allow
                Action: apigateway:*
                Resource: "arn:aws:apigateway:eu-west-1::*"
                
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute

  CompileLambda:
    Type: AWS::Serverless::Function
    Properties: 
      Role: !GetAtt LambdaRole.Arn
      Description: >-
        Compiles a sketch to a binary and puts it to S3
      Handler: compile.handler
      CodeUri: lambda/compile/
      Runtime: provided
      Timeout: 60
      MemorySize: 1024
      Layers: 
        - !Ref CompileLayerParameter

  CompileProxyLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !GetAtt LambdaRole.Arn
      Handler: index.handler
      Code:
        ZipFile: !Sub |
          const AWS = require('aws-sdk');const lambda = new AWS.Lambda();
          exports.handler = (event, context, callback) => {
              const params = {
                FunctionName: "${CompileLambda}",
                InvocationType: "Event",
                Payload: "{ \"data\": \"TestPayload\" }"
              };
              lambda.invoke(params, (err, data) => {
                if(err) {
                  console.log(err, err.stack);
                  callback(null, {
                    statusCode: 500
                  });
                } else {
                  console.log(data);
                  callback(null, {
                    statusCode: 200,
                    body: JSON.stringify({message: "Compile Request submitted"})
                  });
                }
              });
          	};
      Description: Register a connection to the WS API

  CompileProxyRouteIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref WebsocketsAPI
      Description: Lambda Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CompileProxyLambda.Arn}/invocations"

  CompileProxyRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    DependsOn:
      - CompileProxyRouteIntegration
    Properties:
      ApiId: !Ref WebsocketsAPI
      RouteKey: compile
      AuthorizationType: NONE
      Target: !Sub "integrations/${CompileProxyRouteIntegration}"

  ConnectLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !GetAtt LambdaRole.Arn
      Handler: index.handler
      Code:
        ZipFile: !Sub |
          const AWS = require('aws-sdk');const ddb = new AWS.DynamoDB.DocumentClient();
          function addConnectionId(connectionId) {
              return ddb.put({
          		TableName: '${ConnectionsTable}',
                  Item: {
          			connectionid : connectionId
          		},
          	}).promise();
          }
          exports.handler = (event, context, callback) => {
              const connectionId = event.requestContext.connectionId;
              addConnectionId(connectionId).then(() => {
              callback(null, {
          		statusCode: 200,
                  })
          	});
          }
      Description: Register a connection to the WS API

  ConnectRouteIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref WebsocketsAPI
      Description: Lambda Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectLambda.Arn}/invocations"

  ConnectRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    DependsOn:
      - ConnectRouteIntegration
    Properties:
      ApiId: !Ref WebsocketsAPI
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub "integrations/${ConnectRouteIntegration}"

  DisconnectLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !GetAtt LambdaRole.Arn
      Handler: index.handler
      Code:
        ZipFile: !Sub |
          const AWS = require('aws-sdk');const ddb = new AWS.DynamoDB.DocumentClient();
          function removeConnectionId(connectionId) {
              return ddb.delete({
          		TableName: '${ConnectionsTable}',
                  Key: {
          			connectionid : connectionId
          		},
          	}).promise();
          }
          exports.handler = (event, context, callback) => {
              const connectionId = event.requestContext.connectionId;
              removeConnectionId(connectionId).then(() => {
              callback(null, {
          		statusCode: 200,
                  })
          	});
          }
      Description: Deregister a connection to the WS API

  DisconnectRouteIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref WebsocketsAPI
      Description: Lambda Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisconnectLambda.Arn}/invocations"

  DisconnectRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    DependsOn:
      - DisconnectRouteIntegration
    Properties:
      ApiId: !Ref WebsocketsAPI
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub "integrations/${DisconnectRouteIntegration}"

  DefaultLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !GetAtt LambdaRole.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = (event, context, callback) => {
            callback(null, { statusCode: 200 })
          }
      Description: Handles otherwise unhandled routes

  DefaultRouteIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref WebsocketsAPI
      Description: Lambda Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DefaultLambda.Arn}/invocations"

  DefaultRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    DependsOn:
      - DefaultRouteIntegration
    Properties:
      ApiId: !Ref WebsocketsAPI
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Sub "integrations/${DefaultRouteIntegration}"

  ConnectionsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - 
          AttributeName: "connectionid"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "connectionid"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: !Sub "${EnvironmentParameter}-robocoder-ws-connections"

  ConnectLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebsocketsAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ConnectLambda
      Principal: apigateway.amazonaws.com

  DisconnectLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebsocketsAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DisconnectLambda
      Principal: apigateway.amazonaws.com
         
  DefaultLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebsocketsAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DefaultLambda
      Principal: apigateway.amazonaws.com

  CompileProxyLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebsocketsAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CompileProxyLambda
      Principal: apigateway.amazonaws.com
